### PR TITLE
Fix handling of very compressed files

### PR DESCRIPTION
**Pull request by magnetised**
Fixes an edge case where a very compressed file could cause a
:data_error if the decode_close function receives a final chunk that
expands to hundreds of times the size of the original data.

### CODE REVIEW

**Comment by ananthakumaran** [comment]
> Decompresses as much data as possible

I don't know if I interpreted the erlang documentation incorrectly. I might have assumed if we call with the final chunk, it would return all the remaining data as we have supplied the full zip file and it should be possible to decompress everything.  Not sure if it's some issue with the erlang implementation itself or not documented correctly.

I haven't got time to test it yet, will try to do it soon. I am willing to merge the patch as it is (as it's better than the current implementation). 

That said, there are 2 things I am thinking of
1) The inflateChunk API seems to be deprecated and safeInflate is available from OTP 20. Probably we should consider using safeInflate? Conditional compilation based on otp version is another option
2) Zstream.Decoder.code itself should be changed return something `{:more, data, state}`, this might result in some refactoring. Accumulating the value doesn't seem like the perfect fix.

**Comment by magnetised** [comment]
> I might have assumed if we call with the final chunk, it would return all the remaining data as we have supplied the full zip file and it should be possible to decompress everything

Yeah, it's not obvious what's going on. I spent a lot of time looking for off-by-one errors etc but the behaviour of Zstream seemed absolutely perfect. The only hint I saw was a mention in `inflateChunk` about handling very compressed files. My current model is that the `inflate` call doesn't always return all the data it could if the compression ratio is high so when you call close on the zlib state it hasn't flushed its buffers, or something...

> Accumulating the value doesn't seem like the perfect fix.

Agreed! The above is a "fix something broken" patch -- we hit this edge case in production -- but as I wrote it the reality of accumulating potentially massive files into ram instead of streaming out the results was very much in my mind. It would require some tweaking of the state machine but I'm happy to take that on.

> The inflateChunk API seems to be deprecated

oops! I actually tried a version with `safeInflate` and it didn't fix the problem. That may have been because I didn't also set the buffer size. I'll have another look. Now I have a test case it'll be much easier.

I'm super busy this week but I'll be able to have another pass next week (probably).

**Comment by magnetised** [comment]
I've just pushed my latest iteration. It removes the need to accumulate the results of `inflateChunk/2` by instead returning a Stream from `decode/2`.

This works well but unfortunately has the side-effect of requiring some external state held in an ETS table, since we need to keep track of crc32 sums and uncompressed sizes within the streams.

This adds a supervisor and other cruft to Zstream, which I'm not sure you'll like, but I can't see another way of avoiding buffering the results of `inflateChunk` within the unzip state machine without (instead) buffering the source data.

Note, I tried using `safeInflate/2` instead of the deprecated `inflateChunk` but it triggered the exact same bug.

I see you've created an issue in `erlang/otp` - good idea. I'll mention the `safeInflate` issue there too.

**Comment by magnetised** [comment]
Seems the root cause is fixed in OTP master but do you think this streaming approach is still useful if we say move to `safeInflate/2` which returns uncompressed data in chunks?

BTW I left an implementation of `decode/2` using `safeInflate/2` in the above push

**Comment by ananthakumaran** [comment]
Yes, upgrading OTP is the correct fix for this. I definitely want to switch to `safeInflate/2`, will check if it's possible to simplify the implementation later.

**Comment by ananthakumaran** [comment]
@magnetised please review https://github.com/ananthakumaran/zstream/pull/10 when you get time. I will wait for the OTP patch before merging it to master.

**Comment by ananthakumaran** [comment]
published `0.6.0` to hex.

**Pull request closed without merging**
